parameters: {}
environment: {}
packages:
  - name: sample
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: handler
        binary: false
        main: "handler.py"
        runtime: python:default
        web: true
        webSecure: false
        parameters: {}
        environment:
          OPENAI_API_KEY: ${env:OPENAI_API_KEY}
        annotations: {}
        limits: {}
